pipeline "{
   agent {
     laabel {
	    environment {
		    NAME= shubham
			ROLE=devops 
			AGE= 
			}
		}
		
	stages {
       stage (" dir ")
          steps {
             echo "hello"
               sh "date"
                sh "mkdir fusion"			
                sh ls
				}
			}
		}
	}	
